Accept=Onartu
Close=Itxi
Price= Prezioa
SelectOption=Aukeratu
Welcome=Ongi etorri

MainGUI.CreateSale= Eskaintza sortu
MainGUI.QuerySales= Eskaintzak kontsultatu
MainGUI.SelectOption=Aukeratu
MainGUI.MainTitle=Merkatua

CreateSaleGUI.Title=Tituloa
CreateSaleGUI.Description=Deskripzioa
CreateSaleGUI.Status=Egoera
CreateSaleGUI.Category=Kategoria
CreateSaleGUI.Price=Prezioa
CreateSaleGUI.PriceMustBeGreaterThan0=ERROR, prezioa 0 baino handiagoa
CreateSaleGUI.ProductCreated=Eskaintza sortuta
CreateSaleGUI.CreateProduct=Sortu Eskaintza
CreateSaleGUI.ErrorNumber=Error, prezioa zenbaki bat izan behar da
CreateSaleGUI.ErrorQuery=Error, datuak falta dira
CreateSaleGUI.LoadPicture=Argazkia igo
CreateSaleGUI.PublicationDate=Argitarapen eguna

QuerySalesGUI.Search=Bilatu
QuerySalesGUI.NoProducts=Ez daude eskaintzak
QuerySalesGUI.Price=Prezioa
QuerySalesGUI.FindProducts=Eskaintzak bilatu
QuerySalesGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)

ShowSaleGUI.Title=Eskaintza xehestasunak
ShowSaleGUI.LoginAlert=Erosketa burutzeko saioa hasi behar duzu.
ShowSaleGUI.LoginAlertTitle=Saioa hasi gabe

ShowSaleGUI.MainTitle=Produktuaren xehetasunak
ShowSaleGUI.ImageError=Irudia kargatzean errorea
ShowSaleGUI.ShureText=Ziur zaude '
ShowSaleGUI.DeleteQuestion=' produktua kendu nahi duzula?
ShowSaleGUI.ShureButton=Baieztatu
ShowSaleGUI.ConfirmDeleted=Produktua ondo kendu da.
ShowSaleGUI.DeletingError=Errorea produktua kentzerakoan.
ShowSaleGUI.DeleteButton=KENDU
ShowSaleGUI.BuyButton=EROSI


DataAccess.SaleAlreadyExist=ERROR, Eskaintza existizen da
DataAccess.ErrorSaleMustBeLaterThanToday=ERROR, data gaur baino beranduago izan behar da
DataAccess.ErrorFileNotUploadedException=ERROR, Argazkia igo behar da

Identify=Identifikatu
AukerakIkusiGUI.IndetifyLabel=Identifikatu
AukerakIkusiGUI.Title=Saioa hasi nahi?
AukerakIkusiGUI.RegisterButton=Erregistratu
AukerakIkusiGUI.LoginButton=Hasi Saioa
AukerakIkusiGUI.ContinueButton=Saioa hasi gabe jarraitu

AukerakSortuGUI.Title=Identifikatu saltzeko

BizumGUI.Maintitle=Bizumekin erosketa egiten
BizumGUI.PayButton=Bizumekin ordaindu
BizumGUI.Title=Bizum
BizumGUI.AskTlfLabel=Telefono zenbakia
BizumGUI.Add=Gehitu
BizumGUI.Withdraw=Atera
BizumGUI.Done=Eginda

ErosketaGUI.MainTitle=Aukeratu erosteko
ErosketaGUI.NotSelectedLabel=Errorea: Ez da produkturik aukeratu

ErregistratuGUI.MainTitle=Erregistratzen
ErregistratuGUI.NameLabel=Izen abizenak
PasswordLabel=Pasahitza
ErregistratuGUI.RepeatPasswordLabel=Errepikatu pasahitza
ErregistratuGUI.CompleteFieldAlert=Mesedez hutsune guztiak bete
ErregistratuGUI.PasswordError1=Pasahitzak 8-12 karaktere artean izan behar ditu eta gutxienez:
ErregistratuGUI.PasswordError2=Hizki larri bat, hizki xehe bat, zenbaki bat eta karaktere bat.
ErregistratuGUI.DifferentPasswordAlert=Pasahitzak ez dira berdinak
ErregistratuGUI.ExistingMailError=E-mail hori jada existitzen da
ErregistratuGUI.CorrectAlert=Erregistroa ondo egina! Orain saioa hasi dezakezu

SaioaHasiGUI.UserModeLabel=Aukeratu erabitzaile modua:
SaioaHasiGUI.SelectSellerOption=Saltzailea
SaioaHasiGUI.SelectBuyerOption=Eroslea
Continue=Jarraitu
SaioaHasiGUI.MainTitle=Saioa hasten
SaioaHasiGUI.IncorrectAlert=Pasahitza edo erabiltzailea ez da zuzena

ErosketaGUI.CardButton=Txartela
ErosketaGUI.TotalLabel=Guztira
ErosketaGUI.ProductLabel=Produktua
ErosketaGUI.MainTitle=Aukeratu
ErosketaGUI.PutMoney=Dirua sartu
ErosketaGUI.WithdrawMoney=Dirua atera

TxartelaGUI.MainTitle=Txartela
TxartelaGUI.PayLabel=Ordainketa:
TxartelaGUI.NameLabel=Izen-abizenak
TxartelaGUI.CardNumberLabel=Txartel zenbakia
TxartelaGUI.DateLabel=Iraungitze-data
TxartelaGUI.PayButton=Ordaindu
TxartelaGUI.MoneyIn=Dirua gehitu
TxartelaGUI.MoneyOut=Dirua atera
TxartelaGUI.ErrorData=Datuak ez dira zuzenak
TxartelaGUI.ActionGood=Eragiketa ondo burutu da!

ProfilaGUI.Hello=Kaixo, 
ProfilaGUI.Money=Saldoa: 
ProfilaGUI.Wallet=Diruzorroa ikusi
ProfilaGUI.BuyList=Erositako produktuen zerrenda
ProfilaGUI.MainTitle=Profila
ProfilaGUI.BuyerProfile=Erosle profila
ProfilaGUI.SellerProfile=Saltzaile profila
ProfilaGUI.FindProducts=Produktu berriak bilatu
ProfilaGUI.SellProduct=Produktu bat saldu
ProfilaGUI.Product=Produktua
ProfilaGUI.Price=Prezioa
ProfilaGUI.Date=Data
ProfilaGUI.Reclamation=Erreklamazioa
ProfilaGUI.Object=Objetua
ProfilaGUI.PutReclamation=Erreklamazioa jarri
ProfilaGUI.SeeReclamationState=Ikusi egoera
ProfilaGUI.Description=Deskribapena
ProfilaGUI.Solution=Soluzioa
ProfilaGUI.Buyer=Eroslea
ProfilaGUI.YourSales=Zure salmentak
ProfilaGUI.ReceivedReclamations=Jasotako erreklamazioak
ProfilaGUI.Procesing=Prosezatzen...
ProfilaGUI.State=Egoera
ProfilaGUI.Profile=Profila
ProfilaGUI.AskForButton=Eskaria egin

AdminGUI.Solved=Ebatzita
AdminGUI.Seller=Saltzailea
AdminGUI.SelectNewState=Aukeratu egoera berri bat
AdminGUI.ChangeState=Egoera aldatu
AdminGUI.Admmited=Onartua
AdminGUI.Opened=Zabalik
AdminGUI.WriteSolution=Idatzi soluzio bat:
AdminGUI.AddSolution=Geitu soluzioa
AdminGUI.StateGood=Egoera ondo aldatu da
AdminGUI.SelectReclamation=Mesedez, aukeratu erreklamazio bat
AdminGUI.Refused=Baztertua

TransakzioakGUI.Type=Mota
TransakzioakGUI.Concept=Kontzeptua
TransakzioakGUI.Cuantity=Kantitatea
TransakzioakGUI.AddMoney=Gehitu dirua
TransakzioakGUI.WithdrawMoney=Atera dirua
TransakzioakGUI.Wallet=Diruzorroa
TransakzioakGUI.MoreThanZero=Sartu 0 baino handiagoa den balio bat
TransakzioakGUI.NoMoneyMessage=Ez dago diru nahikorik
TransakzioakGUI.NoMOneyTitle=Dirua falta
TransakzioakGUI.InvalidNumberTitle=Zenbaki baliogabea
TransakzioakGUI.InvalidNumberMessage=Sartu baliodun zenbaki bat mesedez
TransakzioakGUI.HowManyWithdraw=Esan zenbat atera nahi duzun
TransakzioakGUI.HowManyAdd=Esan zenbat sartu nahi duzun

ErreklamazioaSortuGUI.ExplainProblem=Azaldu arazoa
ErreklamazioaSortuGUI.SendReclamation=Bidali erreklamazioa
ErreklamazioaSortuGUI.WriteExplication=Idatzi eta azaladu arazoa
ErreklamazioaSortuGUI.ReclamationGood=Erreklamazioa ongi bidali da
ErreklamazioaSortuGUI.ErrorSending=Errorea egon da erreklamazioaren bidalketan

AukerakErosiGUI.List=Saltzaileen zerrenda
AukerakErosiGUI.Product=Produktuak kontsultatu

AdminAukGUI.Admin=Administratzailea
AdminAukGUI.LogOut=Kontua itxi
AdminAukGUI.Reclamation=Erreklamazioak kudeatu
AdminAukGUI.List=Zerrenda beltza

KontuaItxi.Tittle=Kontua Itxi

SalduAukeratuGUI.Title=Aukeratu




ErosketaAukeraketaGUI.MainTitle=Erosketa Aukerak
ErosketaAukeraketaGUI.Title=Nola bilatu nahi dituzu produktuak?
ErosketaAukeraketaGUI.Sale=Produktuak ikusi
ErosketaAukeraketaGUI.Seller=Saltzaileak ikusi

ErreklamazioaSortuGUI.MainTitle=Erreklamazioa

EskariaGUI.Title=Idatz itzazu eskatu nahi dituzun produktuaren datuak
EskariaGUI.Name=Izena:
EskariaGUI.Description=Deskripzioa:
EskariaGUI.MaxPrice=Prezio maximoa:

KontuaItxiGUI.Title=Admin: Kontua Itxi

OfertakGUI.Subtitle=Eskaera
OfertakGUI.Title=Hona hemen zure eskaerarentzat jaso dituzun eskaintzak:
OfertakGUI.MainTitle=Eskaintzak

ProfilaGUI.Basket=Nire saskia
ProfilaGUI.DemanderProfile=Eskatzailearen profila
ProfilaGUI.DeletedProdut=Produktu Ezabatua
ProfilaGUI.Delete=Ezabatu
ProfilaGUI.DemandName=Eskaera Izena
ProfilaGUI.MaxPrice=Prezio Maximoa
ProfilaGUI.Object=Objetua
ProfilaGUI.Action=Ekintza
ProfilaGUI.Sure=Ziur zaude'
ProfilaGUI.SureDelete=' ezabatu nahi duzula?

QueryDemandsGUI.MainTitle=Besteen eskaerak bilatu
QueryDemandsGUI.Title=Hautatu eskaera bat eta egin klik bikoitza produktu bat eskaintzeko:
QueryDemandsGUI.MakeOffer=Hautatutakoari eskaintza egin
QueryDemandsGUI.SelectErrorAlert=Mesedez, hautatu eskaera bat zerrendatik.
QueryDemandsGUI.IdentifyError=Error: Erabiltzailea ez da identifikatu.
QueryDemandsGUI.Name=Izena
QueryDemandsGUI.Description=Deskribapena
QueryDemandsGUI.MaxPrice=Prezio Max.
QueryDemandsGUI.Demander=Eskatzailea
QueryDemandsGUI.Object=Objektua

QuerySellers.MainTitle=Saltzaileak bilatu
QuerySellers.ActiveSellers=Saltzaile Aktiboak
QuerySellers.Name=Izena
QuerySellers.Mail=Emaila
QuerySellers.Object=Objektua

SalduAukeratuGUI.Product=Produktua saldu
SalduAukeratuGUI.OfferToDemand=Eskaera bati eskaintza egin

SestoaGUI.Title=Hautatu saltzaile bat bere produktuak kudeatzeko:
SestoaGUI.MainTitle=Nire Saskia (Saltzaileak)
SestoaGUI.Seller=Saltzailea
SestoaGUI.ProductAmount=Produktu Kopurua
SestoaGUI.SellerObject=Objetua

SestoaSaltzaileanGUI.MainTitle1='
SestoaSaltzaileanGUI.MainTitle2='(r)en produktuak saskian
SestoaSaltzaileanGUI.Product=Produktua
SestoaSaltzaileanGUI.Price=Prezioa
SestoaSaltzaileanGUI.Object=Objektua
SestoaSaltzaileanGUI.BuyAll=Erosi denak
SestoaSaltzaileanGUI.SetEmptyThisSeller=Hustu saltzaile hau
SestoaSaltzaileanGUI.OkayAlert=Erosketa burutu da!

ShowSaleGUI.AddToCart=Saskira gehitu
ShowSaleGUI.Selled=SALDUTA!
ShowSaleGUI.YourProduct=Zure produktua da!
ShowSaleGUI.AddToCartCorrectAlert=Saskira gehitu da!
ShowSaleGUI.LoginToAddToCartAlert=Saioa hasi behar duzu saskira gehitzeko.
ShowSaleGUI.CanNotAddToCartErrorAlert=Ezin izan da produktua saskira gehitu...
ShowSaleGUI.HaveToLogin=Saioa hasi behar duzu.
ShowSaleGUI.SureBuy=Ziur zaude produktua erosi nahi duzula?
ShowSaleGUI.BuyCorrectAlert=Erosketa arrakastaz burutu da.
ShowSaleGUI.IncorrectCurrencyErrorAlert=Errorea: Begiratu zure saldoa.

TransakzioakGUI.MainTitle=Nire transakzioak

ZerrendaBeltzaGUI.MainTitle=Zerrenda Beltza
ZerrendaBeltzaGUI.Title=Blokeatutako erabiltzaileak
ZerrendaBeltzaGUI.ErrorAlert=Errorea zerrenda kargatzean




ProfilaGUI.NoDate=Data gabe
ProfilaGUI.State=Egoera
ProfilaGUI.NoName=Produktu izengabea

OfertakGUI.NoDemand=Ez dago eskaintza erabilgarririk eskaera honentzat.

Welcome=Ongi etorri

SaioaHasiGUI.IncorrectErrorAlert=Email edo pasahitz okerra
SaioaHasiGUI.AccountDisabled=Kontua desgaituta dago

ErregistratuGUI.BlacklistedErrorAlert=Ezin zara erregistratu, email hau zerrenda beltzean dago










KontuaItxiGUI.Sure=Ziur zaude '
KontuaItxiGUI.Ban=' kontua itxi nahi duzula?
KontuaItxiGUI.CorrectBanAlert=Kontua ondo itxi da
KontuaItxiGUI.IncorrectBanErrorAlert=Errorea kontua ixterakoan.
KontuaItxiGUI.Select=Hautatu erabiltzaile bat lehenago!